name: Java CI Pipeline (Build & Test)

on:
  push:
    branches:
      - main
      - develop
      - stage
  pull_request:
    branches:
      - main
      - develop
      - stage

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/ecommerce_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: MySecretPassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_PROFILES_ACTIVE: dev  
      APP_API_PREFIX: /api 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Start Docker Compose services
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for PostgreSQL to be ready
      run: |
        docker-compose logs -f db &
        sleep 20  # Aumenta el tiempo de espera para que PostgreSQL esté listo
        while ! docker exec -t ecommerce_db pg_isready -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -Dspring.profiles.active=test --file pom.xml

    - name: Shutdown Docker Compose
      run: docker-compose -f docker-compose.yml down --volumes --remove-orphans
